import type { Exercise } from '@/types';

/** Gym exercise library — English names, seeded into Dexie on first launch. */
export const EXERCISE_SEED: Exercise[] = [
  { id: 'barbell-bench-press', name: 'Barbell Bench Press', muscleGroup: 'chest', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'incline-barbell-bench-press', name: 'Incline Barbell Bench Press', muscleGroup: 'chest', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', muscleGroup: 'chest', equipment: 'dumbbell', tier: 1, isCustom: false },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', muscleGroup: 'chest', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'chest', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'pec-deck', name: 'Pec Deck', muscleGroup: 'chest', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'machine-chest-press', name: 'Machine Chest Press', muscleGroup: 'chest', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'dumbbell-fly', name: 'Dumbbell Fly', muscleGroup: 'chest', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'machine-fly', name: 'Machine Fly', muscleGroup: 'chest', equipment: 'machine', tier: 1, isCustom: false },
  { id: 'cable-crossover', name: 'Cable Crossover', muscleGroup: 'chest', equipment: 'cable', tier: 1, isCustom: false },
  { id: 'push-up', name: 'Push-Up', muscleGroup: 'chest', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'dip', name: 'Parallel Bar Dip', muscleGroup: 'chest', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'chest-dip', name: 'Chest Dip', muscleGroup: 'chest', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'smith-machine-bench-press', name: 'Smith Machine Bench Press', muscleGroup: 'chest', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'smith-machine-incline-press', name: 'Smith Machine Incline Press', muscleGroup: 'chest', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'decline-barbell-bench-press', name: 'Decline Barbell Bench Press', muscleGroup: 'chest', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'decline-dumbbell-press', name: 'Decline Dumbbell Press', muscleGroup: 'chest', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'low-cable-fly', name: 'Low Cable Fly', muscleGroup: 'chest', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'landmine-press', name: 'Landmine Press', muscleGroup: 'chest', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'close-grip-bench', name: 'Close Grip Bench Press', muscleGroup: 'triceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'deadlift', name: 'Conventional Deadlift', muscleGroup: 'back', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'legs', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'barbell-row', name: 'Barbell Row', muscleGroup: 'back', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'pendlay-row', name: 'Pendlay Row', muscleGroup: 'back', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'back', equipment: 'machine', tier: 1, isCustom: false },
  { id: 'pull-up', name: 'Pull Up', muscleGroup: 'back', equipment: 'bodyweight', tier: 1, isCustom: false },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroup: 'back', equipment: 'cable', tier: 1, isCustom: false },
  { id: 'cable-row', name: 'Cable Row', muscleGroup: 'back', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'hammer-strength-row', name: 'Hammer Strength Row', muscleGroup: 'back', equipment: 'machine', tier: 1, isCustom: false },
  { id: 'hammer-strength-pulldown', name: 'Hammer Strength Pulldown', muscleGroup: 'back', equipment: 'machine', tier: 1, isCustom: false },
  { id: 't-bar-row', name: 'T-Bar Row', muscleGroup: 'back', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'single-arm-dumbbell-row', name: 'Single Arm Dumbbell Row', muscleGroup: 'back', equipment: 'dumbbell', tier: 1, isCustom: false },
  { id: 'straight-arm-pulldown', name: 'Straight Arm Pulldown', muscleGroup: 'back', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'hyperextension', name: 'Hyperextension', muscleGroup: 'back', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'smith-machine-row', name: 'Smith Machine Row', muscleGroup: 'back', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'chest-supported-row', name: 'Chest Supported Row', muscleGroup: 'back', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'meadows-row', name: 'Meadows Row', muscleGroup: 'back', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'cable-pullover', name: 'Cable Pullover', muscleGroup: 'back', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'dumbbell-pullover', name: 'Dumbbell Pullover', muscleGroup: 'back', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'rack-pull', name: 'Rack Pull', muscleGroup: 'back', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'deficit-deadlift', name: 'Deficit Deadlift', muscleGroup: 'back', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', muscleGroup: 'back', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'kroc-row', name: 'Kroc Row', muscleGroup: 'back', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'shoulders', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'overhead-press', name: 'Overhead Press', muscleGroup: 'shoulders', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroup: 'shoulders', equipment: 'dumbbell', tier: 1, isCustom: false },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroup: 'shoulders', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'hammer-strength-shoulder', name: 'Hammer Strength Shoulder Press', muscleGroup: 'shoulders', equipment: 'machine', tier: 1, isCustom: false },
  { id: 'arnold-press', name: 'Arnold Press', muscleGroup: 'shoulders', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroup: 'shoulders', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'machine-lateral-raise', name: 'Machine Lateral Raise', muscleGroup: 'shoulders', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'hammer-strength-lateral', name: 'Hammer Strength Lateral Raise', muscleGroup: 'shoulders', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', muscleGroup: 'shoulders', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'rear-delt-fly', name: 'Rear Delt Fly', muscleGroup: 'shoulders', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'upright-row', name: 'Upright Row', muscleGroup: 'shoulders', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'smith-machine-shoulder-press', name: 'Smith Machine Shoulder Press', muscleGroup: 'shoulders', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'cable-front-raise', name: 'Cable Front Raise', muscleGroup: 'shoulders', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'dumbbell-front-raise', name: 'Dumbbell Front Raise', muscleGroup: 'shoulders', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'rear-delt-cable-fly', name: 'Rear Delt Cable Fly', muscleGroup: 'shoulders', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'machine-rear-delt-fly', name: 'Machine Rear Delt Fly', muscleGroup: 'shoulders', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'plate-front-raise', name: 'Plate Front Raise', muscleGroup: 'shoulders', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'landmine-lateral-raise', name: 'Landmine Lateral Raise', muscleGroup: 'shoulders', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'biceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'dumbbell-curl', name: 'Dumbbell Curl', muscleGroup: 'biceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'biceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'hammer-curl-cable', name: 'Cable Hammer Curl', muscleGroup: 'biceps', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'incline-dumbbell-curl', name: 'Incline Dumbbell Curl', muscleGroup: 'biceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'concentration-curl', name: 'Concentration Curl', muscleGroup: 'biceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'cable-curl', name: 'Cable Curl', muscleGroup: 'biceps', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'ez-bar-curl', name: 'EZ Bar Curl', muscleGroup: 'biceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroup: 'biceps', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'spider-curl', name: 'Spider Curl', muscleGroup: 'biceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'machine-curl', name: 'Machine Curl', muscleGroup: 'biceps', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'reverse-curl', name: 'Reverse Curl', muscleGroup: 'biceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'cross-body-curl', name: 'Cross Body Curl', muscleGroup: 'biceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'tricep-pushdown', name: 'Tricep Pushdown', muscleGroup: 'triceps', equipment: 'cable', tier: 1, isCustom: false },
  { id: 'skull-crusher', name: 'Skull Crusher', muscleGroup: 'triceps', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'overhead-tricep-extension', name: 'Overhead Tricep Extension', muscleGroup: 'triceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'cable-overhead-tricep', name: 'Cable Overhead Tricep', muscleGroup: 'triceps', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'tricep-dip', name: 'Tricep Dip', muscleGroup: 'triceps', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'rope-tricep-extension', name: 'Rope Tricep Extension', muscleGroup: 'triceps', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'machine-tricep-extension', name: 'Machine Tricep Extension', muscleGroup: 'triceps', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'dumbbell-kickback', name: 'Dumbbell Kickback', muscleGroup: 'triceps', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'single-arm-cable-pushdown', name: 'Single Arm Cable Pushdown', muscleGroup: 'triceps', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'back-squat', name: 'Back Squat', muscleGroup: 'legs', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'front-squat', name: 'Front Squat', muscleGroup: 'legs', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'legs', equipment: 'machine', tier: 1, isCustom: false },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'smith-machine-squat', name: 'Smith Machine Squat', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'adductor-machine', name: 'Adductor Machine', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'abductor-machine', name: 'Abductor Machine', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'lying-leg-curl', name: 'Lying Leg Curl', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'seated-leg-curl', name: 'Seated Leg Curl', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'nordic-curl', name: 'Nordic Curl', muscleGroup: 'legs', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'good-morning', name: 'Good Morning', muscleGroup: 'legs', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'walking-lunge', name: 'Walking Lunge', muscleGroup: 'legs', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'legs', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroup: 'legs', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'standing-calf-raise', name: 'Standing Calf Raise', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'seated-calf-raise', name: 'Seated Calf Raise', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'smith-machine-lunge', name: 'Smith Machine Lunge', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'dumbbell-romanian-deadlift', name: 'Dumbbell Romanian Deadlift', muscleGroup: 'legs', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'barbell-lunge', name: 'Barbell Lunge', muscleGroup: 'legs', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'step-up', name: 'Step Up', muscleGroup: 'legs', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'sissy-squat', name: 'Sissy Squat', muscleGroup: 'legs', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'leg-press-calf-raise', name: 'Leg Press Calf Raise', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'pendulum-squat', name: 'Pendulum Squat', muscleGroup: 'legs', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'hip-thrust', name: 'Hip Thrust', muscleGroup: 'glutes', equipment: 'barbell', tier: 1, isCustom: false },
  { id: 'glute-bridge', name: 'Glute Bridge', muscleGroup: 'glutes', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'cable-pull-through', name: 'Cable Pull Through', muscleGroup: 'glutes', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'glute-kickback', name: 'Glute Kickback', muscleGroup: 'glutes', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'smith-machine-hip-thrust', name: 'Smith Machine Hip Thrust', muscleGroup: 'glutes', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'dumbbell-hip-thrust', name: 'Dumbbell Hip Thrust', muscleGroup: 'glutes', equipment: 'dumbbell', tier: 2, isCustom: false },
  { id: 'reverse-hyper', name: 'Reverse Hyper', muscleGroup: 'glutes', equipment: 'machine', tier: 2, isCustom: false },
  {
    id: 'plank',
    name: 'Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    tier: 1,
    isCustom: false,
    timedHold: true,
    note: 'Timed hold — log seconds held per set (not kg).',
  },
  { id: 'crunch', name: 'Crunch', muscleGroup: 'core', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'core', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'core', equipment: 'cable', tier: 2, isCustom: false },
  { id: 'ab-wheel', name: 'Ab Wheel', muscleGroup: 'core', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'russian-twist', name: 'Russian Twist', muscleGroup: 'core', equipment: 'bodyweight', tier: 2, isCustom: false },
  {
    id: 'side-plank',
    name: 'Side Plank',
    muscleGroup: 'core',
    equipment: 'bodyweight',
    tier: 2,
    isCustom: false,
    timedHold: true,
    note: 'Timed hold — log seconds per side per set (not kg).',
  },
  { id: 'decline-crunch', name: 'Decline Crunch', muscleGroup: 'core', equipment: 'bodyweight', tier: 2, isCustom: false },
  { id: 'weighted-crunch', name: 'Weighted Crunch', muscleGroup: 'core', equipment: 'machine', tier: 2, isCustom: false },
  { id: 'landmine-oblique-twist', name: 'Landmine Oblique Twist', muscleGroup: 'core', equipment: 'barbell', tier: 2, isCustom: false },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroup: 'core', equipment: 'cable', tier: 2, isCustom: false },
];
